import "~/styles/globals.css";

import { exo } from "~/utils/fontComponents";
import Link from "next/link";
import GreenButton from "~/components/GreenButton";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${exo.variable}`}>
      <body>
        <div className="font-exo relative flex h-screen w-screen justify-center text-white">
          <div className="rounded-xg bg-glassTexture fixed z-50 mx-10 mt-4 flex h-20 w-full max-w-7xl items-center justify-between px-3 backdrop-blur-xl">
            <Link href="/" className="">
              <img src="../../logo.png" alt="" className="" />
            </Link>
            <div className="flex space-x-6">
              <Link
                href="/"
                className="hover:text-bannerGradientStart ease-in-out"
              >
                Main
              </Link>
              <Link
                href="/"
                className="hover:text-bannerGradientStart ease-in-out"
              >
                Advantages
              </Link>
              <Link
                href="/"
                className="hover:text-bannerGradientStart ease-in-out"
              >
                How to start
              </Link>
              <Link
                href="/"
                className="hover:text-bannerGradientStart ease-in-out"
              >
                Ecosystem
              </Link>
              <Link
                href="/"
                className="hover:text-bannerGradientStart ease-in-out"
              >
                Community
              </Link>
              <Link
                href="/"
                className="hover:text-bannerGradientStart ease-in-out"
              >
                Become a partner
              </Link>
            </div>
            <GreenButton text={"Connect Wallet"} className="w-48" />
          </div>
          <img
            src="../../backgroundPng.png"
            alt="background"
            className="absolute -z-10 h-full w-full object-cover"
          />
          <div className="h-full w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
