/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import "~/styles/globals.css";

import { exo } from "~/utils/fontComponents";
import Link from "next/link";
import GreenButton from "~/components/GreenButton";
import Background from "~/_vectors/Frame";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${exo.variable}`}>
      <body>
        <div className="relative flex h-screen w-screen justify-center font-exo text-white">
          <div className="fixed z-50 mx-10 mt-4 flex h-20 w-full max-w-7xl items-center justify-between rounded-xg bg-glassTexture px-3 backdrop-blur-md">
            <Link href="/" className="">
              <img src="../../logo.png" alt="" className="" />
            </Link>
            <div className="flex space-x-6">
              <Link
                href="/"
                className="ease-in-out hover:text-bannerGradientStart"
              >
                Main
              </Link>
              <Link
                href="/"
                className="ease-in-out hover:text-bannerGradientStart"
              >
                Advantages
              </Link>
              <Link
                href="/"
                className="ease-in-out hover:text-bannerGradientStart"
              >
                How to start
              </Link>
              <Link
                href="/"
                className="ease-in-out hover:text-bannerGradientStart"
              >
                Ecosystem
              </Link>
              <Link
                href="/"
                className="ease-in-out hover:text-bannerGradientStart"
              >
                Community
              </Link>
              <Link
                href="/"
                className="ease-in-out hover:text-bannerGradientStart"
              >
                Become a partner
              </Link>
            </div>
            <GreenButton text={"Connect Wallet"} />
          </div>
          <img
            src="../../backgroundPng.png"
            className="fixed -z-50 h-screen w-screen object-cover"
          />
          <div className="h-full w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
