/* eslint-disable @next/next/no-img-element */
import PageWrapper from "~/components/wrapper/pageWrapper";
import "~/styles/globals.css";

import { exo } from "~/utils/fontComponents";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${exo.variable} scroll-smooth`}>
      <body>
        <PageWrapper>
          <div className="h-full w-full">{children}</div>
        </PageWrapper>
      </body>
    </html>
  );
}
